services:
  playwright:
    container_name: playwright
    image: playwright
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.playwright
    working_dir: /app
    volumes:
      - ${PWD}/:playwright_src
      - playwright_src:/app
    environment:
      SUITE: ${SUITE:-login}
      BROWSER: ${BROWSER:-chrome}
      WORKERS: ${WORKERS:-1}
    networks:
      - project-network

networks:
  project-network:
    external: true

volumes:
  playwright_src:
    name: playwright_src 
    external: true