services:
  playwright:
    container_name: playwright
    image: playwright
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.playwright
    working_dir: /app
    entrypoint: ["sh", "-c", "npm install && ./playwright-entrypoint.sh"]
    volumes:
      - playwright_src:/app
    environment:
      SUITE: ${SUITE}
      BROWSER: ${BROWSER}
      WORKERS: ${WORKERS}
    networks:
      - project-network

networks:
  project-network:
    external: true

volumes:
  playwright_src:
    name: playwright_src
    external: true