services:
  playwright:
    container_name: playwright
    image: playwright
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.playwright
    working_dir: /app
    volumes:
      - .:/app
    environment:
      SUITE: ${SUITE:-login}
      BROWSER: ${BROWSER:-chrome}
    networks:
      - project-network

networks:
  project-network:
    external: true