FROM mcr.microsoft.com/playwright:v1.53.0-noble

# Create working directory
WORKDIR /app

# Copy package files as root
COPY package*.json ./

# Install dependencies as root
RUN npm ci

# Install browsers as root
RUN npx playwright install chrome firefox msedge

# Default command (can be overridden by docker-compose run ...)
CMD ["npm", "run", "test"]
